README.Rmd
README.md

@b-rodrigues this is just a start. Feel free to adapt as needed.

win inst notes

---

README.Rmd
README.md

WIP update win notes

---

README.Rmd
README.md

This is just highlighting single user installation on WSL2.

extra infos for win

---

dev/0-dev_history.Rmd

add ctb infos

---

dev/0-dev_history.Rmd

as discussed on our matrix channel :-)

add Philipp as author

---

README.Rmd
README.md

This is for people to quick-jump to https://b-rodrigues.github.io/rix

Add blue badge "docs | release" with link to official pkgdown site

---

R/find_rev.R
dev/build_envs.Rmd
man/nix_build.Rd

forgot roxygen2 commenting for part of `project_path` arg docs.

`nix_build()`: slightly tweak docs

---

.github/workflows/nix.yaml

add nix build CI

---

R/find_rev.R
dev/build_envs.Rmd

@b-rodrigues I will keep "data.table" for the moment, since I have to first fix the bug complaining. Will then squash the fix into this PR.

add default.nix bootstrapper

---

R/find_rev.R
dev/build_envs.Rmd

deal with `tex_pkgs = NULL`

---

.github/workflows/nix.yaml
.github/workflows/tests-r-via-nix.yaml

added nix magic cache

---

DESCRIPTION
R/get_sri_hash_deps.R

looks i haven't properly removed, so the tests were still failing...

fully remove httr

---

R/fetchers.R

due to changes in how depends were being discovered, packages that were listed like "packageName (> 1.0)" in DESCRIPTION files were causing issues. This should remove the "(...)"

fetchlocals passes?

---

R/with_nix.R

Fix directory creation in with_nix()

---

R/nix_build.R
R/nix_build_helpers.R
R/with_nix.R
tests/testthat/test-fetchers.R
tests/testthat/test-rix.R

Terminate `nix-build` background process for SIGINT interruption via ctrl+c

---

R/get_latest.R

Clearer error message when providing an R version that is too recent

---

R/fetchers.R
tests/testthat/test-fetchers.R

Related https://github.com/ropensci/rix/issues/352

Imports can be empty

---

DESCRIPTION
R/available_r.R
R/get_latest.R

@RichardJActon @jrosell @eliocamp @Kupac @mihem 
you have all contributed to the package, so this PR adds you as ctb.
Let me know if you agree with this (else I'll remove you) and if you agree, check your data. @Kupac I'm missing your email and orcid.

add contributors

---

vignettes/z-advanced-topic-handling-packages-with-remote-dependencies.Rmd

@b-rodrigues I added some more info about git credentials. And also mentioned that this only downloads a maximum of 1000 commits.

Improve docs remote deps

---

vignettes/d1-installing-r-packages-in-a-nix-environment.Rmd

@b-rodrigues see https://github.com/ropensci/rix/issues/527

Docs python install uv

---

DESCRIPTION
NEWS.md
R/fetchers.R
R/tar_nix_ga.R
R/with_nix_helpers.R

fixes #544
