- R/find_rev.R
- dev/build_envs.Rmd
@b-rodrigues I just noticed that the defensive check error in `nix_build()` was still printing a `nix_file` quoting error message. This fixes accordingly the message using `project_path` and `default.nix` in the message.
Since this does not affect the behavior of `nix_build()` but rather just is the error message, I think we do not need to increment versioning using "patch". However, if you want to increment to 0.1.2, I am very happy to do so and update news accordingly
> - `nix_build()`: fix defensive check message

- README.Rmd
- README.md
The only thing I don't know how to tweak the position of where the generated table of contents appears in the README. I have the feeling this might be better fine-controlled with quarto, so I don't know if Rmarkdown via knitr supports adjusting position.
> README: add table of contents

- README.Rmd
- README.md
work in progress; addresses #51
> start drafting "From quickstart to deep dive"

- inst/extdata/default.nix
> fix locale warnings by setting envvars in nix

- R/find_rev.R
- dev/build_envs.Rmd
example before this patch:
```{sh}
spectral-cockpit@localhost  ~/git/philipp-baumann/rix_tests   main ±  cat default.nix 
let
pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/7131f3c223a2d799568e4b278380cd9dac2b8579.tar.gz") {};
rpkgs = builtins.attrValues {
inherit (pkgs.rPackages) languageserver;
};
git_archive_pkgs = [(pkgs.rPackages.buildRPackage {
name = "rix";
src = pkgs.fetchgit {
url = "https://github.com/b-rodrigues/rix";
branchName = "master";
rev = "15d82addb3b60363a2d162be84be2cad74180efc";
sha256 = "sha256-/qX7Z4wk9slr/SYJLxnwvLYZh6UgZDcLald1HN52BNk=";
};
propagatedBuildInputs = builtins.attrValues {
inherit (pkgs.rPackages) httr jsonlite sys;
};
}) ];
system_packages = builtins.attrValues {
inherit (pkgs) R glibcLocalesUtf8 nix radianWrapper quarto; …
```
> fix missing `pkgs.mkShell` when `shell_hook = NULL`

- R/detect_os.R
- R/find_rev.R
- dev/build_envs.Rmd
- dev/get_os.Rmd
- man/rix.Rd
> "older" nixpkgs revisions. Import `glibcLocales` to fix `glibcLocalesUtf8` attribute not found

- R/find_rev.R
- dev/build_envs.Rmd
- man/with_nix.Rd
- these two workhorses can now also run in RStudio on macOS.
- resolves #94
> `with_nix()` and `nix_shell()` in-session fix `PATH` for RStudio on macOS; improve docs

- R/nix_build.R
- dev/config_fusen.yaml
- dev/flat_nix_build.Rmd
- tests/testthat/test-nix_build.R
concerns re-setting `.libPaths()` by removing `R_LIBS_USER`
> `nix_build()`: another guardrail for run-time purity of Nixpkgs R

- R/nix_build.R
- R/with_nix.R
- dev/flat_nix_build.Rmd
- dev/flat_with_nix.Rmd
- tests/testthat/test-nix_build.R
- tests/testthat/test-with_nix.R
- Finally make `nix_build()` and `with_nix()` run on major Linux distros and also make `testthat::test()` pass
> `nix_build()` & `with_nix()`fix segmentation fault with adjusting `LD_LIBRARY_PATH` temporarily

- R/nix_build.R
- R/with_nix.R
- dev/flat_nix_build.Rmd
- dev/flat_with_nix.Rmd
- Relevant when running `covr::package_coverage()` in Nix-R session (covr sets multiple lib paths for `R_LIBS_USER`
> Do not remove `R_LIBS_USER` from .libPaths() in covr test environment

- dev/b2-macos.Rmd
- vignettes/b2-setting-up-and-using-rix-on-macos.Rmd
> Add note on `aarch64-darwin` backwards compatibility for Nixpkgs R

- DESCRIPTION
- R/rix.R
- dev/flat_rix.Rmd
- man/rix.Rd
- tests/testthat/_snaps/rix/rstudio_default.nix
- vignettes/b1-setting-up-and-using-rix-on-linux-and-windows.Rmd
Adds support to RStudio server and radian. It is done in a way that avoids core repetition, and allows easy addition of future wrappers.
In addition, {fusen} also modified some files (vignetters, DESCRIPTION), probably for the better, so I also included those in the commit.
> Add more IDE-s: rserver and radian

- R/rix_init.R
- man/rix_init.Rd
There is a new `message_type = "quiet"` option which writes rix init `.Rprofile` without any message to the user. 
Also, `message_type = "simple"` is a bit slimmer.
*Simple* (default)
```{r}
> rix_init(message_type = "simple")
==> Existing isolated nix-R project folder:
/Users/philipp/git/philipp-baumann-shared/rix 
==> R session running via host operating system or docker
* Keep existing `.Rprofile`. in `project_path`:
/Users/philipp/git/philipp-baumann-shared/rix/ 
==> Also adjusting `PATH` via `Sys.setenv()`, so that system commands can invoke key Nix commands like `nix-build` in this RStudio session on the host operating system.
```
*Quiet*: as expected, doesn't message
```{r}
> rix_init(message_type = "quiet")
```
*Verbose*: output messages help to understand the working principles …
> `rix_init()` implement "quiet" and improve "simple" message_type

- R/with_nix.R
- man/with_nix.Rd
removes an apparent bug reported here: #178 
`nix_file` is legacy and we go for specific `project_path`s for each separate Nix R environment to enforce isolated projects. that means that `shell.nix` will have percedence over `default.nix`, which is how `nix-shell <project_dir>` behaves (we call that process through {sys}.
> Remove `nix_file` interface for `with_nix()`

- R/rix.R
- tests/testthat/test-rix.R
- tests/testthat/test-with_nix.R
- vignettes/a-getting-started.Rmd
For older versions of R, shells could not be built, instead users have to drop into them directly. This is to warn users about that.
> warn users that generate an expression for an old version of R

- vignettes/b1-setting-up-and-using-rix-on-linux-and-windows.Rmd
This change try to make a clear recommendation to avoid system package manager and try to avoid people having isues like this  https://discourse.nixos.org/t/nix-var-nix-daemon-socket-socket-permission-denied/39142
> Reduce confusion installing nix on Linux

- .github/workflows/run_rhub.yaml
- NEWS.md
- R/rix_helpers.R
- README.Rmd
- README.md
final preps for CRAN submission !!
> Fix roxygen2 check note & Update README

- R/nix_hash.R
https://github.com/ropensci/rix/issues/371
This fixes the problem that occurs when there are two Description files resulting in  two paths.
I tried to solve it in a rather generic way, by using `file.path(list.files(path_to_src), "DESCRIPTION")` so only allowing the description file if it's in the root folder. This solves the problem in my use-case, but  @b-rodrigues feel free to change and further test.
> try fixing getting desc_path

- R/rix.R
This fixes a bug introduced here: https://github.com/ropensci/rix/commit/44cf22a694257f094858d2c66bb0767fe58c28e9
Example. This used to work fine:
```
rix(
r_ver = "4.3.1",
r_pkgs = c("dplyr", "ggplot2"),
ide = "code",
project_path = ".",
git_pkgs = list(
package_name = "CSFAtasTools",
repo_url = "https://github.com/mihem/CSFAtlasTools",
commit = "02d485896d383e2a876f0f3bbae7265c017e7e92"
),
overwrite = TRUE
)
```
But now failed with
```
Error in strsplit(cran_pkgs$archive_pkg, split = "@") : 
non-character argument
```
In contrast, if there is a CRAN archive, this works fine:
```
rix(
r_ver = "4.3.1",
r_pkgs = c("dplyr", "ggplot2", "AER@1.2-8"),
ide = "code",
project_path = ".",
git_pkgs = list(
package_name = "CSFAtasTools",
repo_url = "https://github.com/mihem/CSFAtlasTools",
commit = …
```
> Fix handle remote deps

- R/fetchers.R
This tried to fix the following issue:
```
rix(
r_ver = "4.3.1",
r_pkgs = c("dplyr", "ggplot2", "AER@1.2-8"),
ide = "code",
project_path = ".",
git_pkgs = list(
package_name = "CSFAtasTools",
repo_url = "https://github.com/mihem/CSFAtlasTools",
commit = "02d485896d383e2a876f0f3bbae7265c017e7e92"
),
overwrite = TRUE
)
```
works fine.
But adding the remote dependency leads to a double entry of datathin
```
rix(
r_ver = "4.3.1",
r_pkgs = c("dplyr", "ggplot2"),
ide = "code",
project_path = ".",
git_pkgs = list(
list(
package_name = "CSFAtasTools",
repo_url = "https://github.com/mihem/CSFAtlasTools",
commit = "02d485896d383e2a876f0f3bbae7265c017e7e92"
),
list(
package_name = "datathin",
repo_url = "https://github.com/anna-neufeld/datathin",
commit = "58eb154609365fa7301ea0fa397fbf04dd8c28ed"
) …
```
> Fix double installation remote packages

- R/fetchers.R
- R/nix_hash.R
- R/rix_helpers.R
- R/with_nix.R
- README.Rmd
- README.md
I wonder if instead of #396 we shouldn't be instead removing all of this. It's ok to keep files in the temporary directories, what's not ok is:
- writing to the user directory and keeping the files there
- tests or vignettes that write to the user directory and keep the detritus there
I think that this approach would be saner.
> Remove excessive unlinks

- R/fetchers.R
- tests/testthat/test-fetchers.R
@b-rodrigues This tries to implement our idea to also include imports from NAMESPACE; not only from DESCRIPTION.
This was actually easier than I thought. I might have missed something, but the tests seems to pass.
I added tests, one checks if `Seurat` is fetched in `seurat-data`, which we added manually before that because it's not listed in DESCRIPTION.
I fixed a bug which happens because e.g. this CRAN mirror uses quotes. 
https://github.com/cran/AER/blob/master/NAMESPACE
Excited about your revision.
> Remote namespace

- vignettes/z-advanced-topic-handling-packages-with-remote-dependencies.Rmd
@b-rodrigues
A few suggestions, i think it's good to mention that
1. it uses commit dates before but not after the date given.
2. Warning when github pat not set (but might still work)
3. API 403 if there are credentials errors (like hitting API limit)
I've not seen the `url must be string` error before. Is this the full error message you get?
As you write, probably it's because gaborcsardi/gh does not exist anymore? I also thought about using gh for testing, but it's confusing because it's now r-lib/gh so I am not sure this is a good example.
> Update docs remote deps
